# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0006_auto_20160609_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='update_time',
        ),
        migrations.AddField(
            model_name='asteroid',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 14, 30, 33, 438898)),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='num_observations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 14, 30, 33, 439979)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 14, 30, 33, 438643)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 14, 30, 33, 438412)),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('S', 'Scheduled'), ('N', 'Canceled'), ('F', 'Failed')], max_length=1),
        ),
    ]
