# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 16:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0003_auto_20160607_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroid',
            name='timelapse_url',
            field=models.URLField(default='http://'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 7, 16, 13, 58, 663398)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 7, 16, 13, 58, 660729)),
        ),
    ]
