# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0004_auto_20160607_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asteroid',
            name='arc_length',
        ),
        migrations.RemoveField(
            model_name='asteroid',
            name='epochofperih',
        ),
        migrations.RemoveField(
            model_name='asteroid',
            name='perihdist',
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 12, 52, 44, 949200)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='image',
            field=models.CharField(default='no-image.jpg', max_length=50),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 12, 52, 44, 948928)),
        ),
    ]
