# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0007_auto_20160609_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_num', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('S', 'Scheduled'), ('N', 'Canceled'), ('F', 'Failed')], max_length=1)),
                ('last_update', models.DateTimeField(default=datetime.datetime(2016, 6, 14, 13, 20, 43, 250621))),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='asteroid',
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 14, 13, 20, 43, 249188)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 14, 13, 20, 43, 249442)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 14, 13, 20, 43, 248970)),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AddField(
            model_name='observation',
            name='asteroid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observe.Asteroid'),
        ),
    ]
