# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0008_auto_20160614_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='request_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 14, 14, 9, 9, 192665)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 14, 14, 9, 9, 192919)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 14, 14, 9, 9, 192403)),
        ),
        migrations.AlterField(
            model_name='observation',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 14, 14, 9, 9, 194101)),
        ),
    ]
