# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 16:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0009_auto_20160614_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='twitter',
        ),
        migrations.AddField(
            model_name='observation',
            name='frame_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 17, 16, 45, 21, 149980)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 17, 16, 45, 21, 150260)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 17, 16, 45, 21, 149762)),
        ),
        migrations.AlterField(
            model_name='observation',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 17, 16, 45, 21, 151458)),
        ),
    ]
