# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-31 14:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0011_auto_20160618_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroid',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 31, 14, 52, 5, 656841)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='image',
            field=models.FileField(upload_to='teaser'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 31, 14, 52, 5, 657148)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 31, 14, 52, 5, 656591)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='timelapse_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 31, 14, 52, 5, 658516)),
        ),
    ]
