# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0012_auto_20170131_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroid',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 15, 8, 27, 569271)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 15, 8, 27, 569624)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 15, 8, 27, 568925)),
        ),
        migrations.AlterField(
            model_name='observation',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 15, 8, 27, 570909)),
        ),
    ]
