# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-10 20:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0013_auto_20170228_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroid',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 10, 20, 51, 25, 19985)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='epochofel',
            field=models.FloatField(blank=True, null=True, verbose_name='Epoch of elements'),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='instrument',
            field=models.CharField(choices=[('1M0-SCICAM-SBIG', '1m'), ('2M0-SCICAM-SPECTRAL', '2m'), ('0M4-SCICAM-SBIG', '0.4m')], max_length=30),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 10, 20, 51, 25, 20248)),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 10, 20, 51, 25, 19750)),
        ),
        migrations.AlterField(
            model_name='observation',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 10, 20, 51, 25, 21610)),
        ),
    ]
