# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-20 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0015_auto_20171208_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asteroid',
            name='image',
        ),
        migrations.AddField(
            model_name='asteroid',
            name='image_url',
            field=models.URLField(default='https://lco.global/files/astronomy/asteroid/unknown.jpg'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 14, 41, 3, 431318)),
        ),
    ]
