# Generated by Django 2.1.7 on 2019-03-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0019_auto_20190311_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asteroid',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='asteroid',
            old_name='timelapse_url',
            new_name='timelapse',
        ),
    ]
