# Generated by Django 2.1 on 2019-03-18 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0020_auto_20190311_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asteroid',
            old_name='timelapse',
            new_name='timelapse_mpeg',
        ),
        migrations.AddField(
            model_name='asteroid',
            name='timelapse_webm',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='asteroid',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update of timelapse'),
        ),
    ]
