# Generated by Django 2.1.7 on 2019-05-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0021_auto_20190318_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroid',
            name='observe_interval',
            field=models.IntegerField(default=14),
        ),
    ]
