# Generated by Django 2.1.7 on 2019-05-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0022_asteroid_observe_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroid',
            name='semester_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
